"""
Here, we will run everything that is related to the training procedure.
"""

import time
import torch
import torch.nn as nn

from tqdm import tqdm
from utils import train_utils
from torch.utils.data import DataLoader
from utils.types import Scores, Metrics
from utils.train_utils import TrainParams
from utils.train_logger import TrainLogger
import torch.optim as optim
import IPython.display
import numpy as np
import utils.plot as plot
import matplotlib.pyplot as plt




def get_metrics(best_eval_score: float, eval_score: float, train_loss: float) -> Metrics:
    """
    Example of metrics dictionary to be reported to tensorboard. Change it to your metrics
    :param best_eval_score:
    :param eval_score:
    :param train_loss:
    :return:
    """
    return {'Metrics/BestAccuracy': best_eval_score,
            'Metrics/LastAccuracy': eval_score,
            'Metrics/LastLoss': train_loss}


def train(dis_model: nn.Module, gen_model: nn.Module, train_loader: DataLoader, train_params: TrainParams, logger: TrainLogger) -> Metrics:
    dsc_avg_losses, gen_avg_losses = [], []
    dsc_optimizer = torch.optim.Adam(dis_model.parameters(), lr=train_params.lr_des)
    gen_optimizer = torch.optim.Adam(gen_model.parameters(), lr=train_params.lr_gen)
    for epoch_idx in range(train_params.num_epochs):
        # We'll accumulate batch losses and show an average once per epoch.
        dsc_losses, gen_losses = [], []
        print(f'--- EPOCH {epoch_idx+1}/{train_params.num_epochs} ---')

        #with tqdm.tqdm(total=len(train_loader.batch_sampler), file=sys.stdout) as pbar:
        #for idx, (x_data, _) in tqdm(enumerate(train_loader)):
        for x_data in train_loader:
            image = x_data[0]
            features = x_data[1]
            if torch.cuda.is_available():
                image = image.to("cuda")
                features = features.to("cuda")
            dsc_loss, gen_loss = train_batch(dis_model, gen_model, discriminator_loss_fn, generator_loss_fn, dsc_optimizer, gen_optimizer, image, features)
            dsc_losses.append(dsc_loss)
            gen_losses.append(gen_loss)

        dsc_avg_losses.append(np.mean(dsc_losses))
        gen_avg_losses.append(np.mean(gen_losses))
        print(f'Discriminator loss: {dsc_avg_losses[-1]}')
        print(f'Generator loss:     {gen_avg_losses[-1]}')
        
        if save_checkpoint(gen_model, dsc_avg_losses, gen_avg_losses, 'checkpoint'):
            print(f'Saved checkpoint.')
            

        """samples = gen_model.sample(5, with_grad=False)
        fig, _ = plot.tensors_as_images(samples.cpu(), figsize=(6,2))
        IPython.display.display(fig)
        plt.close(fig)

    # Show hypers
    print(hp)"""

def discriminator_loss_fn(y_data, y_generated, data_label=1, label_noise=0.3):
    """
    Computes the combined loss of the discriminator given real and generated
    data using a binary cross-entropy metric.
    This is the loss used to update the Discriminator parameters.
    :param y_data: Discriminator class-scores of instances of data sampled
    from the dataset, shape (N,).
    :param y_generated: Discriminator class-scores of instances of data
    generated by the generator, shape (N,).
    :param data_label: 0 or 1, label of instances coming from the real dataset.
    :param label_noise: The range of the noise to add. For example, if
    data_label=0 and label_noise=0.2 then the labels of the real data will be
    uniformly sampled from the range [-0.1,+0.1].
    :return: The combined loss of both.
    """
    assert data_label == 1 or data_label == 0
    device = y_generated.device
    norm_label_noise = 0.5 * label_noise

    min_value, max_value =  [data_label-norm_label_noise, data_label+norm_label_noise]
    diff = max_value-min_value
    noisy_data_label = min_value + torch.rand(y_data.shape, device=device)*diff

    min_value, max_value =  [1-data_label-norm_label_noise, 1-data_label+norm_label_noise]
    diff = max_value - min_value
    generated_label = min_value + torch.rand(y_generated.shape, device=device)*diff
    
    loss_func = torch.nn.BCEWithLogitsLoss(reduction='mean')
    
    loss_data = loss_func(y_data, noisy_data_label)
    loss_generated = loss_func(y_generated, generated_label)
    return loss_data + loss_generated

def generator_loss_fn(y_generated, data_label=1):
    """
    Computes the loss of the generator given generated data using a
    binary cross-entropy metric.
    This is the loss used to update the Generator parameters.
    :param y_generated: Discriminator class-scores of instances of data
    generated by the generator, shape (N,).
    :param data_label: 0 or 1, label of instances coming from the real dataset.
    :return: The generator loss.
    """
    assert data_label == 1 or data_label == 0
    device = y_generated.device
    
    generated_labeles = torch.ones(y_generated.shape, device=device)
    generated_labeles = data_label * generated_labeles
    loss_func = torch.nn.BCEWithLogitsLoss()
    loss = loss_func(y_generated, generated_labeles)
    return loss

def create_optimizer(model_params, opt_params):
    opt_params = opt_params.copy()
    optimizer_type = opt_params['type']
    opt_params.pop('type')
    return optim.__dict__[optimizer_type](model_params, **opt_params)

def train_batch(
    dsc_model,
    gen_model,
    dsc_loss_fn,
    gen_loss_fn,
    dsc_optimizer,
    gen_optimizer,
    #x_data,
    image,
    features,
):
    """
    Trains a GAN for over one batch, updating both the discriminator and
    generator.
    :return: The discriminator and generator losses.
    """

    dsc_optimizer.zero_grad()
    
    #real images
    y_data = dsc_model.forward(image)
    
    #generate data w/o grad
    generated_data = gen_model.sample(image.shape[0], features, with_grad=False)

    #fake images w/o grad
    y_generated = dsc_model.forward(generated_data.detach())

    #fix y shape
    y_data = y_data.view(-1)
    y_generated = y_generated.view(-1)
    
    dsc_loss = dsc_loss_fn(y_data, y_generated)
    dsc_loss.backward(retain_graph=True)
    dsc_optimizer.step()

    gen_optimizer.zero_grad()
    
    #generate data w/ grad
    generated_data_2 = gen_model.sample(image.shape[0], features, with_grad=True)

    #fake images w/ grad
    y_generated_2 = dsc_model(generated_data_2)

    #fix y shape
    y_generated = y_generated.view(-1)
    
    gen_loss = gen_loss_fn(y_generated_2.view(-1)) 
    gen_loss.backward()
    gen_optimizer.step()

    return dsc_loss.item(), gen_loss.item()

def save_checkpoint(gen_model, dsc_losses, gen_losses, checkpoint_file):
    """
    Saves a checkpoint of the generator, if necessary.
    :param gen_model: The Generator model to save.
    :param dsc_losses: Avg. discriminator loss per epoch.
    :param gen_losses: Avg. generator loss per epoch.
    :param checkpoint_file: Path without extension to save generator to.
    """

    saved = False
    gen_len = len(gen_losses)
    checkpoint_file = f"output/{checkpoint_file}"+str(gen_len)+".pt"
    """new_arr = []
    for i in range(len(gen_losses)):
        new_arr.append(1/(abs(dsc_losses[i] - gen_losses[i])*(dsc_losses[i] + gen_losses[i])))
    tmp = max(new_arr)
    predicted_index = new_arr.index(tmp)
    if (predicted_index == len(gen_losses)-11):
        torch.save(gen_model, checkpoint_file)
        saved = True"""
    #min_value = min(gen_losses)
    #if (min_value == gen_losses[gen_len-1]):
    torch.save(gen_model, checkpoint_file)
    saved = True
    return saved
