defaults:
  - hydra/job_logging: disabled
  - hydra/output_subdir: null
hydra:
  output_subdir: null
  run:
    dir: logs/hydra
main:
  experiment_name_prefix: my_exp
  seed: 1
  num_workers: 6
  parallel: False
  gpus_to_use: 1,2
  trains: False
  image_shape: 64
  paths:
    train: 'data/CelebA/img_align_celeba'
    validation: 'data/validation.pkl'
    logs: 'logs/'
train:
  num_epochs: 150
  grad_clip: 0.25
  dropout: 0.2
  num_hid: 20
  batch_size: 512
  in_channel: 3
  z_shape: 128
  save_model: False
  lr:
    lr_gen_value: 0.0001
    lr_des_value: 0.000008
