defaults:
  - hydra/job_logging: disabled
  - hydra/output_subdir: null
hydra:
  output_subdir: null
  run:
    dir: logs/hydra
main:
  experiment_name_prefix: my_exp
  seed: 1
  num_workers: 6
  parallel: False
  gpus_to_use: 1,2
  trains: False
  paths:
    train: 'data/train.pkl'
    validation: 'data/validation.pkl'
    logs: 'logs/'
train:
  num_epochs: 15
  grad_clip: 0.25
  dropout: 0.2
  num_hid: 20
  batch_size: 16
  save_model: False
  lr:
    lr_value: 1e-3
    lr_decay: 15
    lr_gamma: 0.1
    lr_step_size: 30